### ISSUE TITLE
Flicker and non-controllable app on iPadOS

### ISSUE THREAD

**Issue by Ghostbird** [bcc-code/bcc-media-app#377] opened 2024-05-01 19:19 UTC
An older woman, friend of my mother's showed me that her BCC Media app isn't working. I reinstalled it from the App Store, but that didn't help. This is on iPadOS 15.8.2. I don't know the hardware version, I forgot to note it.

The behaviour I observed most closely matched [this flutter issue](https://github.com/flutter/flutter/issues/128221), especially the video in that bug report. I observed similar flickering side-bars.

I tried to film it, using my phone, but in that video it isn't as clear as I saw it earlier.

https://github.com/bcc-code/bcc-media-app/assets/1202149/83db1e50-91af-4c83-9fc2-87f81c46bb62

> [!NOTE]
> Video is recorded in slow-motion to better show the flicker.

**Comment by andreasgangso** [comment] 2024-05-03 12:17
Thanks for notifying us. I'll look into it next week 👍

**Comment by Ghostbird** [comment] 2024-05-10 10:49
Any luck?

**Comment by mulundapm** [comment] 2024-05-13 07:33
Fix is now in review. Will be in production after iOS's approval.

**Comment by Ghostbird** [comment] 2024-05-13 08:53
Thanks a lot!

**Comment by Ghostbird** [comment] 2024-06-06 19:29
I just got called by this same old lady, and the problem was gone after the fix, but has returned now. I have no clue what could have caused that.

**Comment by Ghostbird** [comment] 2024-06-08 13:25
And now it's gone again.

**Comment by mulundapm** [comment] 2024-07-12 15:34
This issue still exists and we have temporally disabled the feature that is causing this. Will close this once the route cause is fixed

**Comment by Ghostbird** [comment] 2024-07-15 15:09
Thanks a lot!

**Comment by Ghostbird** [comment] 2024-07-16 19:11
Any ETA on the release?

**Comment by andreasgangso** [comment] 2024-07-16 19:15
> Any ETA on the release?

Is it still happening now? This shouldn't be happening on any versions right now, as we disabled the "quote of the day" section which we found to be causing this.

**Comment by Ghostbird** [comment] 2024-07-16 20:13
I just got a call, but told her it would be fixed in the next version.

**Comment by andreasgangso** [comment] 2024-07-17 10:49
I couldn't reproduce this after I switched out the webview v5.6.8 @mulundapm

**Closed** 2024-07-17 11:42 UTC

**Comment by Ghostbird** [comment] 2024-07-17 19:27
Seems to be solved indeed.
